"""
Core Layer: The Agent Runtime.
Integrates Cortex (Reasoning), Executive (Safety), and Synapse (Tools).
"""
import json
from typing import Callable, Dict, Any, Optional

from aeon.cortex.reasoning import Cortex, CortexConfig
from aeon.synapse.adapter import SynapseAdapter
from aeon.executive.safety import ExecutiveRegistry

class Agent:
    """
    The Neuro-Symbolic Agent Runtime.
    Orchestrates the flow between LLM reasoning (Cortex), Tool use (Synapse),
    and Deterministic Control (Executive).
    """
    def __init__(self, name: str, mcp_server_path: str):
        self.name = name
        
        # Initialize Architecture Layers
        self.cortex = Cortex(CortexConfig())
        self.synapse = SynapseAdapter(mcp_server_path)
        self.executive = ExecutiveRegistry()
        
        # System Prompt defines the Identity
        self.system_prompt = f"""
        You are {name}, an industrial safety controller.
        You have access to hardware sensors via tools.
        Use them to fulfill user requests efficiently.
        """

    def axiom(self, on_violation: str = "OVERRIDE") -> Callable:
        """
        Decorator to register a safety axiom in the Executive layer.
        """
        return self.executive.register(name="axiom", on_violation=on_violation)

    async def start(self):
        """
        Boot sequence for the agent runtime.
        """
        print(f"AEON KERNEL v0.1.0 | {self.name}")
        print("-" * 40)
        await self.synapse.connect()

    async def stop(self):
        """
        Graceful shutdown sequence.
        Closes connections to prevent asyncio errors.
        """
        if self.synapse:
            await self.synapse.disconnect()
        print("-" * 40)
        print("AEON KERNEL SHUTDOWN")

    async def process(self, user_input: str):
        """
        The Neuro-Symbolic Loop:
        1. Tool Discovery (Synapse)
        2. Reasoning (Cortex)
        3. Safety Check (Executive Axioms)
        4. Execution (Synapse)
        """
        print(f"\n [>] User Input: {user_input}")

        # 1. Get Tools from Synapse (MCP)
        try:
            tools = await self.synapse.get_tool_definitions()
        except Exception as e:
            print(f" [!] Error fetching tools from Synapse: {e}")
            return

        # 2. Cortex Reasoning (LLM)
        # The LLM decides WHICH tool to call based on input and available tools
        llm_decision = self.cortex.plan_action(self.system_prompt, user_input, tools)

        # Check if the LLM actually wants to call a tool or just chat
        if not hasattr(llm_decision, 'function'):
            print(f" [i] Cortex Response (No Action): {llm_decision}")
            return

        # Parse the intended action
        tool_name = llm_decision.function.name
        
        # Robust JSON Parsing (LLMs often make mistakes here)
        try:
            tool_args = json.loads(llm_decision.function.arguments)
        except json.JSONDecodeError:
            print(" [!] Cortex Error: Invalid JSON generated by LLM.")
            return
        
        print(f" [i] Cortex Intent: Call {tool_name} with {tool_args}")

        # 3. EXECUTIVE CONTROL (The Axiom Layer)
        # This is the "Prefrontal Cortex" intervening before action.
        # We validate the ARGUMENTS before the tool is executed.
        try:
            safe_args = self.executive.validate_output(tool_args)
        except Exception as e:
            # If the axiom blocked execution completely (raised AxiomViolationError)
            print(f" [!] BLOCKED by Executive: {e}")
            return

        # 4. Synapse Execution (Action)
        # Execute with safe_args (which might have been modified by the Axiom/Override)
        try:
            result = await self.synapse.execute_tool(tool_name, safe_args)
            
            # Extract text content from MCP result for display
            output_text = result.content[0].text if result.content else "No output"
            print(f" [<] Tool Output: {output_text}")
            
        except Exception as e:
            print(f" [!] Synapse Error during tool execution: {e}")